logging:
  config: ${LOGGING_CONFIG:classpath:logback-spring.xml}

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  servlet.session.timeout: 24h

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
#   "update" - create database, only for pet projects, not for any prod projects
      ddl-auto: update
#      ddl-auto: validate
      format_sql: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/testexample}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  thymeleaf:
    mode: HTML
    cache: false
#    only for dev
#    prefix: file:src/main/resources/templates/
  mvc:
    static-path-pattern: /static/**

#logging:
#    config: classpath:logback-custom.xml