spring:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
#   "update" - create database, only for pet projects, not for any prod projects
      ddl-auto: update
#      ddl-auto: validate
      format_sql: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/testexample_test}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
